package com.xnotes.ui

import android.content.Context
import androidx.compose.material3.LocalTextStyle
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.text.TextLayoutResult
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.TextUnit

/**
 * Keeps the existing English UI strings intact and supplies Simplified Chinese at the display
 * boundary. This deliberately avoids touching document data, filenames, format tokens, or URLs.
 */
@Composable
internal fun localizedText(text: String): String {
    val locales = LocalConfiguration.current.locales
    return if (locales.isEmpty) text else localizedText(locales[0], text)
}

internal fun localizedText(context: Context, text: String): String {
    val locales = context.resources.configuration.locales
    return if (locales.isEmpty) text else localizedText(locales[0], text)
}

private fun localizedText(locale: java.util.Locale, text: String): String {
    val traditional = locale.script == "Hant" || locale.country in setOf("TW", "HK", "MO")
    return if (locale.language == "zh" && !traditional) zhHans(text) else text
}

/** Material Text with the app's lightweight display-time localisation applied. */
@Composable
internal fun Text(
    text: String,
    modifier: Modifier = Modifier,
    color: Color = Color.Unspecified,
    fontSize: TextUnit = TextUnit.Unspecified,
    fontStyle: FontStyle? = null,
    fontWeight: FontWeight? = null,
    fontFamily: FontFamily? = null,
    letterSpacing: TextUnit = TextUnit.Unspecified,
    textDecoration: TextDecoration? = null,
    textAlign: TextAlign? = null,
    lineHeight: TextUnit = TextUnit.Unspecified,
    overflow: TextOverflow = TextOverflow.Clip,
    softWrap: Boolean = true,
    maxLines: Int = Int.MAX_VALUE,
    minLines: Int = 1,
    onTextLayout: ((TextLayoutResult) -> Unit)? = null,
    style: TextStyle = LocalTextStyle.current,
) {
    androidx.compose.material3.Text(
        text = localizedText(text),
        modifier = modifier,
        color = color,
        fontSize = fontSize,
        fontStyle = fontStyle,
        fontWeight = fontWeight,
        fontFamily = fontFamily,
        letterSpacing = letterSpacing,
        textDecoration = textDecoration,
        textAlign = textAlign,
        lineHeight = lineHeight,
        overflow = overflow,
        softWrap = softWrap,
        maxLines = maxLines,
        minLines = minLines,
        onTextLayout = onTextLayout,
        style = style,
    )
}

private val ZH_HANS = mapOf(
    ".xnote file" to ".xnote 文件",
    "A handwriting notes and sketching app for Android" to "Android 手写笔记与素描应用",
    "A note must keep at least one page." to "笔记必须至少保留一页。",
    "AREA" to "范围",
    "About" to "关于",
    "Accent colour" to "强调色",
    "Activate during hover (no need to touch the screen)" to "悬停时启用（无需触碰屏幕）",
    "Add" to "添加",
    "Add bookmark" to "添加书签",
    "Add page" to "添加页面",
    "Add section" to "添加分组",
    "Add stickers…" to "添加贴纸…",
    "Alignment" to "对齐",
    "All Pages" to "所有页面",
    "Applies to the selected strokes and shapes." to "应用于所选笔迹和形状。",
    "Ascending" to "升序",
    "Auto" to "自动",
    "Back" to "返回",
    "Back to home" to "返回首页",
    "Bold" to "粗体",
    "Bookmarks" to "书签",
    "Bottom" to "底部",
    "Brightness" to "亮度",
    "Bring to front" to "置于顶层",
    "Bullet list" to "项目符号列表",
    "Button 1" to "按键 1",
    "Button 2" to "按键 2",
    "Cancel" to "取消",
    "Calligraphy" to "书法笔",
    "CALLIGRAPHY" to "书法笔",
    "CHANGE STYLE" to "更改样式",
    "Change folder" to "更改文件夹",
    "Change style" to "更改样式",
    "Checkbox item" to "复选框项目",
    "Choose a folder to keep and browse your notes in." to "选择一个用于保存和浏览笔记的文件夹。",
    "Choose folder" to "选择文件夹",
    "Classic accent" to "经典强调色",
    "Clear clipboard" to "清空剪贴板",
    "Clear search" to "清除搜索",
    "Clear selection" to "取消选择",
    "Close this pane" to "关闭此窗格",
    "Code block" to "代码块",
    "Code highlighting" to "代码高亮",
    "Code theme" to "代码主题",
    "Code theme imported." to "已导入代码主题。",
    "COLOUR" to "颜色",
    "Collapse sidebar" to "收起侧边栏",
    "Color code" to "颜色标记",
    "Colour" to "颜色",
    "Colour palette" to "调色板",
    "Colours" to "颜色",
    "Contents" to "目录",
    "Contrast" to "对比度",
    "Copy" to "复制",
    "Copy as image" to "复制为图片",
    "Copy version" to "复制版本号",
    "Could not export to PDF." to "无法导出为 PDF。",
    "Could not import that font." to "无法导入该字体。",
    "Could not open that note." to "无法打开该笔记。",
    "Could not open the note." to "无法打开笔记。",
    "Could not open the second note." to "无法打开第二个笔记。",
    "Could not read the file." to "无法读取文件。",
    "Could not read the image." to "无法读取图片。",
    "Could not read the sticker." to "无法读取贴纸。",
    "Could not save a copy." to "无法保存副本。",
    "Could not save the image." to "无法保存图片。",
    "Could not save the images." to "无法保存图片。",
    "Could not save the note." to "无法保存笔记。",
    "Could not share the note." to "无法分享笔记。",
    "Could not share the pages." to "无法分享页面。",
    "Couldn't store the theme file." to "无法保存主题文件。",
    "Couldn’t copy the image." to "无法复制图片。",
    "Couldn’t create that folder." to "无法创建该文件夹。",
    "Couldn’t create the canvas." to "无法创建画布。",
    "Couldn’t create the note." to "无法创建笔记。",
    "Couldn’t delete some items." to "无法删除部分项目。",
    "Couldn’t move some items." to "无法移动部分项目。",
    "Couldn’t paste some items here." to "无法在此处粘贴部分项目。",
    "Couldn’t rename the note." to "无法重命名笔记。",
    "Couldn’t save that note." to "无法保存该笔记。",
    "Cover" to "封面",
    "Create" to "创建",
    "Current Page" to "当前页面",
    "Custom" to "自定义",
    "Custom theme" to "自定义主题",
    "Cut" to "剪切",
    "DASH" to "虚线",
    "DASHED" to "虚线笔",
    "Dashed" to "虚线笔",
    "Dark" to "深色",
    "Date modified" to "修改日期",
    "Default" to "默认",
    "Default code language" to "默认代码语言",
    "Default for all notes" to "所有笔记的默认值",
    "Default for new notes" to "新笔记的默认值",
    "Default page size" to "默认页面大小",
    "Delete" to "删除",
    "Delete section" to "删除分组",
    "Delete?" to "删除？",
    "Descending" to "降序",
    "Deselect" to "取消选择",
    "Disappearing ink" to "消失墨迹",
    "Discard" to "放弃",
    "Document" to "文档",
    "Documents" to "文档",
    "Done" to "完成",
    "Dots" to "点阵",
    "Double" to "双页",
    "Draw with finger (off = finger pans)" to "用手指绘制（关闭时手指用于平移）",
    "Duplicate" to "创建副本",
    "ERASER" to "橡皮擦",
    "Enjoying xnotes? " to "喜欢 xnotes？",
    "Erase page" to "清空页面",
    "Eraser" to "橡皮擦",
    "Export to PDF" to "导出为 PDF",
    "Exported to PDF." to "已导出为 PDF。",
    "Exporting to PDF…" to "正在导出 PDF…",
    "FILL" to "填充",
    "File" to "文件",
    "Filename template" to "文件名模板",
    "Fit" to "适应",
    "Fit all" to "显示全部",
    "Fit page height" to "适应页面高度",
    "Fit page width" to "适应页面宽度",
    "Fit whole page" to "显示完整页面",
    "Folder name" to "文件夹名称",
    "Font" to "字体",
    "Fonts" to "字体",
    "Forget folder" to "忘记文件夹",
    "Full screen" to "全屏",
    "GAP" to "间隔",
    "General" to "常规",
    "Grid" to "网格",
    "GL unavailable" to "GL 不可用",
    "GO" to "跳转",
    "GO TO PAGE" to "跳转到页面",
    "Height (mm)" to "高度（毫米）",
    "Help make xnotes better" to "帮助改进 xnotes",
    "Hide page borders" to "隐藏页面边框",
    "Highlighter" to "荧光笔",
    "HIGHLIGHTER" to "荧光笔",
    "Higher feels smoother when you pan and zoom but uses more memory. Your ink and PDFs look just as crisp either way." to "设置越高，平移和缩放越流畅，但会使用更多内存。无论如何设置，墨迹和 PDF 都会保持清晰。",
    "Home" to "首页",
    "Image" to "图片",
    "IMAGE" to "图片",
    "Image (PNG)" to "图片（PNG）",
    "Image copied. Paste it anywhere." to "图片已复制，可在任意位置粘贴。",
    "Import" to "导入",
    "Import PDF" to "导入 PDF",
    "Import PDF…" to "导入 PDF…",
    "Import a .ttf or .otf to offer it in the text font pickers." to "导入 .ttf 或 .otf 文件，以便在文本字体列表中使用。",
    "Import a Helix editor theme (.toml) to recolour code." to "导入 Helix 编辑器主题（.toml）以更改代码颜色。",
    "Import font…" to "导入字体…",
    "Import theme…" to "导入主题…",
    "Importing PDF…" to "正在导入 PDF…",
    "Importing note…" to "正在导入笔记…",
    "Importing…" to "正在导入…",
    "Indent" to "增加缩进",
    "Input" to "输入",
    "INTENSITY" to "强度",
    "INVERSE" to "反向",
    "Insert image" to "插入图片",
    "Insert image…" to "插入图片…",
    "Invert" to "反色",
    "Italic" to "斜体",
    "Landscape" to "横向",
    "Larger" to "放大",
    "Lasso" to "套索",
    "LASSO" to "套索",
    "Left" to "左侧",
    "Letter" to "Letter",
    "Light" to "浅色",
    "Lines" to "横线",
    "Loading…" to "正在加载…",
    "Lock" to "锁定",
    "Lock zoom" to "锁定缩放",
    "Lock zoom at fit width" to "在适应宽度时锁定缩放",
    "Margins" to "页边距",
    "MARGINS" to "页边距",
    "Margins (mm)" to "页边距（毫米）",
    "Material You" to "Material You",
    "MAX ZOOM" to "最大缩放",
    "MIN ZOOM" to "最小缩放",
    "Minimap" to "小地图",
    "Mono font" to "等宽字体",
    "More" to "更多",
    "MULTIPLIER" to "倍率",
    "Name" to "名称",
    "New" to "新建",
    "New Canvas" to "新建画布",
    "New Note" to "新建笔记",
    "New canvas" to "新画布",
    "New folder" to "新建文件夹",
    "New note" to "新笔记",
    "New notes" to "新笔记",
    "NEON" to "发光效果",
    "GLOW INTENSITY" to "发光强度",
    "Next page" to "下一页",
    "No pan" to "不平移",
    "No saved views yet." to "尚无已保存视图。",
    "No stickers yet." to "尚无贴纸。",
    "None" to "无",
    "Not a usable Helix theme (a self-contained .toml is needed)." to "不是可用的 Helix 主题（需要独立的 .toml 文件）。",
    "Not an xnotes document." to "该文件不是 xnotes 文档。",
    "Note" to "笔记",
    "OLED" to "OLED",
    "OPACITY" to "不透明度",
    "Open side by side" to "并排打开",
    "Open with" to "打开方式",
    "Open…" to "打开…",
    "Opening note…" to "正在打开笔记…",
    "Ordered list" to "有序列表",
    "Orientation" to "方向",
    "Outdent" to "减少缩进",
    "PDF" to "PDF",
    "PAGE COLOUR" to "页面颜色",
    "PAPER" to "纸张",
    "PATTERN" to "纹理",
    "PATTERN COLOUR" to "纹理颜色",
    "PDF COLOUR FILTERS" to "PDF 颜色滤镜",
    "PRESSURE" to "压感",
    "Page" to "页面",
    "Page colour" to "页面颜色",
    "Page colour follows the theme" to "页面颜色跟随主题",
    "Page nav" to "页面导航",
    "Page options" to "页面选项",
    "Pages" to "页面",
    "Pan" to "平移",
    "PAN" to "平移",
    "Panning while zoom is locked" to "锁定缩放时的平移方式",
    "Paste" to "粘贴",
    "Paste as Code" to "粘贴为代码",
    "Paste as Markdown" to "粘贴为 Markdown",
    "Paste here" to "粘贴到此处",
    "Paste image" to "粘贴图片",
    "Pen" to "钢笔",
    "PEN" to "钢笔",
    "Performance" to "性能",
    "Portrait" to "纵向",
    "Preferences" to "偏好设置",
    "Preparing…" to "正在准备…",
    "Previous page" to "上一页",
    "RECENT" to "最近使用",
    "Redmi Smart Pen side buttons (tap)" to "Redmi Smart Pen 侧键（点按）",
    "Redo" to "重做",
    "REDO" to "重做",
    "Remove" to "移除",
    "Rename" to "重命名",
    "Rename folder" to "重命名文件夹",
    "Rename note" to "重命名笔记",
    "Report a bug" to "报告问题",
    "Request a feature" to "功能建议",
    "Reset" to "重置",
    "Reset to defaults" to "恢复默认设置",
    "Right" to "右侧",
    "Root" to "根目录",
    "Ruler" to "直尺",
    "RULER" to "直尺",
    "SAVE THIS VIEW" to "保存此视图",
    "SCALE" to "缩放比例",
    "SCROLLBAR" to "滚动条",
    "SCREENSHOT" to "截图",
    "Screenshot" to "截图",
    "SELECT" to "选择",
    "SENSITIVITY" to "压感灵敏度",
    "SHAPE" to "形状",
    "Shape" to "形状",
    "SIZE" to "大小",
    "Save" to "保存",
    "Save a copy…" to "保存副本…",
    "Save as" to "另存为",
    "Save as…" to "另存为…",
    "Saving your notes…" to "正在保存笔记…",
    "Search notes" to "搜索笔记",
    "Searching…" to "正在搜索…",
    "Select" to "选择",
    "Selected" to "已选择",
    "Sepia" to "复古棕",
    "Share" to "分享",
    "Share note" to "分享笔记",
    "Share…" to "分享…",
    "Show sidebar" to "显示侧边栏",
    "Side panel" to "侧边栏",
    "Sidebar" to "侧边栏",
    "Single" to "单页",
    "Single-finger pan" to "单指平移",
    "Size" to "大小",
    "Size (pt)" to "大小（磅）",
    "Smaller" to "缩小",
    "Snap held strokes to shapes (hold the pen still)" to "长按笔画后转换为形状（保持笔尖不动）",
    "Sort by" to "排序方式",
    "SPACING" to "间距",
    "SPEED" to "速度笔",
    "Speed" to "速度笔",
    "Spectrum" to "光谱",
    "Sponsor" to "赞助",
    "Star it on GitHub" to "在 GitHub 上加星",
    "Start in fullscreen" to "启动时全屏",
    "Sticker" to "贴纸",
    "Stickers" to "贴纸",
    "Strikethrough" to "删除线",
    "Styles" to "样式",
    "STRAIGHT LINE" to "直线",
    "STROKE" to "笔迹",
    "STYLES" to "样式",
    "SWITCH BACK" to "切换回去",
    "Stylus double-tap" to "手写笔双击",
    "Stylus side button (tap)" to "手写笔侧键（点按）",
    "Stylus/Pen side button (hold)" to "手写笔侧键（按住）",
    "Swatches" to "色板",
    "System" to "跟随系统",
    "Tap a tool to show or hide it. Long-press to drag it within or across sections. Long-press a section's top to move the whole section." to "点按工具以显示或隐藏。长按可在分组内或分组间拖动。长按分组顶部可移动整个分组。",
    "Tap to insert, hold to remove" to "点按插入，长按移除",
    "Taper" to "收尖笔",
    "TAPER" to "收尖笔",
    "Text" to "文本",
    "TEXT" to "文本",
    "Text box" to "文本框",
    "TEXT_BOX" to "文本框",
    "That page is already empty." to "该页面已经为空。",
    "The clipboard has no image to paste." to "剪贴板中没有可粘贴的图片。",
    "Theme" to "主题",
    "This folder has no notes." to "此文件夹中没有笔记。",
    "This may take a moment." to "这可能需要一点时间。",
    "Three-finger tap" to "三指点按",
    "THICKNESS" to "粗细",
    "TIP WIDTH PERCENTAGE" to "笔尖宽度百分比",
    "Title" to "标题",
    "Toggle eraser" to "切换橡皮擦",
    "Toggle pan" to "切换平移",
    "Toggle previous tool" to "切换上一个工具",
    "Toolbar" to "工具栏",
    "Top" to "顶部",
    "Two-finger pan" to "双指平移",
    "Two-finger tap" to "双指点按",
    "UI theme" to "界面主题",
    "Underline" to "下划线",
    "Undo" to "撤销",
    "UNDO" to "撤销",
    "Unlock" to "解锁",
    "Unlock zoom" to "解锁缩放",
    "Unsaved changes" to "未保存的更改",
    "Untitled" to "未命名",
    "Use App Storage" to "使用应用存储",
    "VERTICAL SCROLLING" to "纵向滚动",
    "Version copied" to "版本号已复制",
    "View" to "视图",
    "VIEW" to "视图",
    "VIEWING MODE" to "查看模式",
    "Waypoints" to "保存的视图",
    "WAYPOINTS" to "保存的视图",
    "WIDTH" to "笔画宽度",
    "Width (mm)" to "宽度（毫米）",
    "Writing the PDF…" to "正在写入 PDF…",
    "YYYY YY MM DD HH mm ss expand to the creation date and time. # becomes the number " to "YYYY YY MM DD HH mm ss 会展开为创建日期和时间。# 会变为序号 ",
    "Zoom" to "缩放",
    "ZOOM" to "缩放",
    "Zoom in" to "放大",
    "Zoom lock" to "缩放锁定",
    "Zoom out" to "缩小",
    "\"Paste as Code\" highlights the pasted block in this language." to "“粘贴为代码”会使用此语言高亮粘贴的代码块。",
    "all pages" to "所有页面",
    "drop here" to "放到此处",
    "inherit the document default" to "继承文档默认设置",
    "plain (no highlighting)" to "纯文本（无高亮）",
    "the list has stopped moving" to "列表已停止移动",
    "that keeps the name free in its folder." to "以确保文件夹中的名称不重复。",
    "what I see" to "当前所见",
    "— no bookmarks —" to "— 没有书签 —",
    "— no table of contents —" to "— 没有目录 —",
    "‹  Save as" to "‹  另存为",
    "‹  Share as" to "‹  分享为",
    ".xcanvas file" to ".xcanvas 文件",
    "Default for new canvases" to "设为新画布默认样式",
    "Disable front buffering" to "禁用前缓冲绘制",
    "Front buffering paints the pen's ink straight into the frame the screen is showing, which is what makes it feel instant. A few panels do not hand that over cleanly, and there the ink can flicker or fall behind the nib. Turn it off on those and every stroke goes through the ordinary canvas." to "前缓冲绘制可降低笔迹延迟。部分屏幕可能出现笔迹闪烁或跟笔延迟，遇到这些问题时可关闭此功能，使用常规画布绘制。",
    "Stylus primary button (hold)" to "笔主按钮（按住）",
    "Stylus secondary button (hold)" to "笔副按钮（按住）",
    "S Pen third-party dual-button compatibility" to "S Pen 第三方笔双按钮兼容",
    "Treat eraser-tip input as the secondary button. For compatible third-party pens such as Wacom One. This also remaps a physical tail eraser while enabled." to "适用于 Wacom One 等兼容笔，将橡皮擦输入识别为副按钮。开启后，其他笔的笔尾橡皮擦也会使用副按钮配置。",
    "Screen" to "滤色",
    "Multiply" to "正片叠底",
    "Tint" to "着色",
    "Off" to "关闭",
    "ROTATE" to "旋转",
    "TOP" to "顶部",
    "BOTTOM" to "底部",
    "LEFT" to "左侧",
    "RIGHT" to "右侧",
    "  mono" to "  等宽",
)

internal fun zhHans(text: String): String {
    ZH_HANS[text]?.let { return it }

    Regex("Page (\\d+)").matchEntire(text)?.let { return "第 ${it.groupValues[1]} 页" }
    Regex("Version (.+)").matchEntire(text)?.let { return "版本 ${it.groupValues[1]}" }
    Regex("Share “(.+)” as:").matchEntire(text)?.let { return "将“${it.groupValues[1]}”分享为：" }
    Regex("Share (.+)").matchEntire(text)?.let { return "分享 ${it.groupValues[1]}" }
    Regex("Save changes to “(.+)” before continuing\\?").matchEntire(text)?.let {
        return "继续之前保存对“${it.groupValues[1]}”的更改？"
    }
    Regex("Delete (\\d+) items\\? This can’t be undone\\.").matchEntire(text)?.let {
        return "删除 ${it.groupValues[1]} 个项目？此操作无法撤销。"
    }
    Regex("Delete “(.+)”\\? This can’t be undone\\.").matchEntire(text)?.let {
        return "删除“${it.groupValues[1]}”？此操作无法撤销。"
    }
    Regex("No notes match “(.+)”\\.").matchEntire(text)?.let {
        return "没有与“${it.groupValues[1]}”匹配的笔记。"
    }
    Regex("Saved (\\d+) images?\\.").matchEntire(text)?.let { return "已保存 ${it.groupValues[1]} 张图片。" }
    Regex("Writing (\\d+) pages?…").matchEntire(text)?.let { return "正在写入 ${it.groupValues[1]} 页…" }
    Regex("Writing (\\d+) items?…").matchEntire(text)?.let { return "正在写入 ${it.groupValues[1]} 个对象…" }
    Regex("item (\\d+) / (\\d+)").matchEntire(text)?.let { return "对象 ${it.groupValues[1]} / ${it.groupValues[2]}" }
    Regex("page (\\d+) / (\\d+)").matchEntire(text)?.let { return "第 ${it.groupValues[1]} / ${it.groupValues[2]} 页" }
    Regex("Refining PDF colours (\\d+)/(\\d+) pages…").matchEntire(text)?.let {
        return "正在优化 PDF 颜色 ${it.groupValues[1]}/${it.groupValues[2]} 页…"
    }
    Regex("Font “?\"?(.+?)\"?”? imported\\.").matchEntire(text)?.let {
        return "已导入字体“${it.groupValues[1]}”。"
    }
    Regex("Max cache resolution\\s+(\\d+) px").matchEntire(text)?.let {
        return "最大缓存分辨率  ${it.groupValues[1]} px"
    }
    Regex("Side margin\\s+(.+)").matchEntire(text)?.let { return "侧边距  ${it.groupValues[1]}" }
    Regex("Colours on the toolbar\\s+(\\d+)").matchEntire(text)?.let {
        return "工具栏颜色  ${it.groupValues[1]}"
    }
    Regex("The next note would be named (.+)").matchEntire(text)?.let {
        return "下一个笔记将命名为 ${it.groupValues[1]}"
    }
    Regex("This note changed elsewhere\\. Your edits are now in “(.+)”\\.").matchEntire(text)?.let {
        return "此笔记已在其他位置更改。你的编辑现已保存在“${it.groupValues[1]}”中。"
    }
    Regex("This canvas changed elsewhere\\. Your edits are now in “(.+)”\\.").matchEntire(text)?.let {
        return "此画布已在其他位置更改。你的编辑现已保存在“${it.groupValues[1]}”中。"
    }

    return text
}
